[appstore]
referrer = "https://apps.apple.com/"
# api_host configured via APP_STORE_API_HOST in environment secrets
api_path = "v1/catalog/{country}/apps/{app_id}/reviews"
limit    = 20

[http]
timeout_seconds     = 10s
max_retries         = 3
backoff_initial_sec = 1s
backoff_max_sec     = 60s
user_agents = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322)",
    "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko",
    "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)"
]

[kafka]
brokers     = ["kafka:9092"]
group_id    = "ingestor"

[postgres]
# dsn configured via PG_DSN in environment secrets